#!/bin/bash
rundir=/data/proteus/jrt51/turb_Ekman_test
codedir=./for

echo $rundir

# copy grid files from run dir
cd $codedir
cp $rundir/grid* ./

# load any module files that you need
module load diablo_2d
module load ifort
module load hdf5/parallel
module load mpich/3.0.4

# compile the code
make clean
make

# copy the executable back to the run dir
cp diablo $rundir/diablo

# to run the code, you could do one of the following
cd $rundir
# for parallel run:
mpirun -np 4 diablo 
# for serial run:
# diablo >output.dat &
